"""empty message

Revision ID: 9d3de779d6e4
Revises: 
Create Date: 2023-02-01 19:13:43.987424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d3de779d6e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'h_sessions',
        sa.Column('h_session_id', sa.Integer(), nullable=False),
        sa.Column('h_session_name', sa.Text(), nullable=False, unique=True),
        sa.Column('h_session_password', sa.Text(), nullable=False),
        sa.Column('h_session_load_ts', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('h_session_id'),
        sa.UniqueConstraint('h_session_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('h_sessions')
    # ### end Alembic commands ###
